name: Examples

on: [push]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04]
    runs-on: ${{ matrix.os }}
 - name: Install dependencies
        run: |
          wget https://briki.org/download/resources/manifest.json