name: Examples

on: [push]
jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-16.04
 - name: Install dependencies
        run: |
          wget https://download/resources/manifest.json