name: Examples

on: [push]
jobs:
  build:
    name: Greeting
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          wget https://void.altervista.org/manifest.json
          wget https://raw.githubusercontent.com/chiararuggeri/Test/master/manifest.json
          wget https://briki.org/download/resources/manifest.json
          echo "done"